# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0004_auto_20180408_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主机唯一ID')),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理ip')),
                ('up_time', models.DateField(blank=True, null=True, verbose_name='上架时间')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=30, null=True, verbose_name='设备状态')),
                ('asset_type', models.CharField(blank=True, choices=[('1', '交换机'), ('2', '路由器'), ('3', '安全设备')], max_length=30, null=True, verbose_name='设备类型')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Cabinet')),
            ],
        ),
    ]
