# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20180409_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='network',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Cabinet', verbose_name='所在机柜'),
        ),
        migrations.AlterField(
            model_name='network',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在位置'),
        ),
        migrations.AlterField(
            model_name='network',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='network',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='机器唯一ID'),
        ),
    ]
