# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20180410_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='network',
            name='productname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机器型号'),
        ),
        migrations.AddField(
            model_name='network',
            name='user_passwd',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名/密码'),
        ),
        migrations.AddField(
            model_name='network',
            name='vender',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='厂商名称'),
        ),
        migrations.AlterField(
            model_name='network',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='过保时间'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='管理IP'),
        ),
    ]
