# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20180411_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='hostname',
            field=models.CharField(max_length=100, null=True, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='network',
            name='productname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='设备型号'),
        ),
    ]
