# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20180412_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name='管理IP'),
        ),
    ]
