# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20180416_0443'),
        ('network', '0006_auto_20180413_0707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='network',
            unique_together=set([('cabinet', 'floor')]),
        ),
    ]
