# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20180419_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='u',
            field=models.IntegerField(blank=True, null=True, verbose_name='U数'),
        ),
    ]
