# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import utils.jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64, unique=True, verbose_name='任务名称')),
                ('task_describe', models.CharField(max_length=256, verbose_name='任务描述')),
                ('task_machines', models.TextField(verbose_name='任务机器')),
                ('task_status', models.CharField(choices=[('0', '未开始'), ('1', '执行中'), ('2', '已完成'), ('3', '执行失败')], default='0', max_length=3, verbose_name='任务状态')),
                ('playbook_name', models.CharField(blank=True, max_length=64, null=True)),
                ('playbook_content', models.TextField()),
                ('create_user', models.CharField(max_length=64, verbose_name='创建者')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('finish_at', models.DateTimeField(auto_now=True)),
                ('task_result', utils.jsonfield.fields.JSONField(max_length=-1, verbose_name='执行结果')),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='CrontabTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_name', models.CharField(max_length=64, unique=True, verbose_name='计划名称')),
                ('cron_describe', models.CharField(max_length=256, verbose_name='计划描述')),
                ('cron_machines', models.TextField(verbose_name='任务机器')),
                ('cron_status', models.CharField(choices=[('0', '未添加'), ('1', '已添加'), ('1', '已删除')], default='0', max_length=1, verbose_name='计划状态')),
                ('cron_schedule', utils.jsonfield.fields.JSONField()),
                ('cmd', models.TextField()),
                ('create_user', models.CharField(max_length=64, verbose_name='创建者')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
    ]
