# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontabtasks',
            name='cron_status',
            field=models.CharField(choices=[('0', '未添加'), ('1', '已添加'), ('2', '已删除')], default='0', max_length=1, verbose_name='计划状态'),
        ),
    ]
