# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import utils.jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180518_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crontabtasks',
            name='cron_status',
        ),
        migrations.AddField(
            model_name='crontabtasks',
            name='playbook_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='crontabtasks',
            name='playbook_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='crontabtasks',
            name='run_user',
            field=models.CharField(default='root', max_length=64, verbose_name='计划所属用户'),
        ),
        migrations.AddField(
            model_name='crontabtasks',
            name='task_result',
            field=utils.jsonfield.fields.JSONField(default={}, max_length=-1, verbose_name='执行结果'),
        ),
        migrations.AddField(
            model_name='crontabtasks',
            name='task_status',
            field=models.CharField(choices=[('0', '未添加'), ('1', '执行中'), ('2', '已添加'), ('3', '添加失败'), ('4', '已删除')], default='0', max_length=1, verbose_name='计划状态'),
        ),
    ]
