# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender', models.CharField(max_length=100, verbose_name='厂商')),
                ('version', models.CharField(max_length=100, verbose_name='版本号')),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='机柜名称')),
                ('address', models.CharField(max_length=200, verbose_name='机柜位置')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100, verbose_name='型号')),
                ('cores', models.CharField(blank=True, max_length=10, null=True, verbose_name='每颗核数')),
                ('count', models.CharField(blank=True, max_length=10, null=True, verbose_name='总核数')),
                ('phyical', models.CharField(blank=True, max_length=10, null=True, verbose_name='座数')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EngineRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='机房名称')),
                ('address', models.CharField(max_length=100, verbose_name='机房位置')),
                ('city', models.CharField(max_length=100, verbose_name='所在城市')),
                ('floor', models.CharField(max_length=100, verbose_name='所在层数')),
                ('account_manager', models.CharField(max_length=100, verbose_name='客户经理')),
                ('phone', models.CharField(max_length=100, verbose_name='电话')),
                ('ip_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='ip范围')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主机唯一ID')),
                ('hostname', models.CharField(max_length=100, null=True)),
                ('os', models.CharField(max_length=20, null=True)),
                ('os_version', models.CharField(max_length=200, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理ip')),
                ('up_time', models.DateField(blank=True, null=True, verbose_name='上架时间')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=30, null=True, verbose_name='设备状态')),
                ('asset_type', models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器'), ('4', '网络设备'), ('5', '安全设备'), ('6', '其他')], max_length=30, null=True, verbose_name='设备类型')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='大小')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='类型')),
                ('speed', models.CharField(blank=True, max_length=10, null=True, verbose_name='速度')),
                ('sn', models.CharField(blank=True, max_length=10, null=True, verbose_name='sn')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.CharField(max_length=100, verbose_name='名称')),
                ('mac', models.CharField(max_length=100, verbose_name='mac地址')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv4地址')),
                ('ipv4_netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv4地址')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv6地址')),
                ('ipv6_netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv6地址')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Host')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Host'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Host'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.EngineRoom'),
        ),
        migrations.AddField(
            model_name='bios',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Host'),
        ),
    ]
