# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目组')),
                ('contacts', models.CharField(max_length=100, verbose_name='联系人')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='servers.Team'),
            preserve_default=False,
        ),
    ]
