# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20180408_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='容量'),
        ),
        migrations.AddField(
            model_name='disk',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sn码'),
        ),
        migrations.AddField(
            model_name='disk',
            name='vender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='account_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='机房位置'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在层数'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='engineroom',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Cabinet'),
        ),
        migrations.AlterField(
            model_name='host',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contacts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
    ]
