# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20180408_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器')], max_length=30, null=True, verbose_name='设备类型'),
        ),
    ]
