# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20180408_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mem',
            name='vender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='厂商'),
        ),
    ]
