# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20180409_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=100, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(max_length=20, null=True, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_version',
            field=models.CharField(max_length=200, null=True, verbose_name='系统版本'),
        ),
    ]
