# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_auto_20180409_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='mange_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='主机ip'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='系统类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_version',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='系统版本'),
        ),
    ]
