# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20180409_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Cabinet', verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='host',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Team', verbose_name='所属项目组'),
        ),
    ]
