# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_host_kernel'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='end_time',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='主机过保时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='productname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机器型号'),
        ),
        migrations.AddField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SN码'),
        ),
        migrations.AddField(
            model_name='host',
            name='vender',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ipv4_netmask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv4掩码'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ipv6_netmask',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ipv6掩码'),
        ),
    ]
