# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_auto_20180410_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='u_number',
            field=models.IntegerField(blank=True, default=48, verbose_name='U数'),
        ),
        migrations.AddField(
            model_name='host',
            name='app_note',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='应用描述'),
        ),
        migrations.AddField(
            model_name='host',
            name='floor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='所在位置'),
        ),
        migrations.AddField(
            model_name='host',
            name='note',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='host',
            name='responsible',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='责任人'),
        ),
    ]
