# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_auto_20180410_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='主机ip'),
        ),
    ]
