# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_auto_20180411_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='user_passwd',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名/密码'),
        ),
    ]
