# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0016_host_user_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='end_time',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='过保时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='主机IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='kernel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='内核版本'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mange_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vender',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='厂商名称'),
        ),
    ]
