# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0017_auto_20180412_0245'),
        ('servers', '0017_auto_20180412_0217'),
    ]

    operations = [
    ]
