# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_auto_20180413_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='node',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='所属主机'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('cabinet', 'floor')]),
        ),
    ]
