# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20180416_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='floor',
            field=models.CharField(blank=True, default='多位置以-连接', max_length=30, null=True, verbose_name='所在位置'),
        ),
    ]
