# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0020_auto_20180416_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sn'),
        ),
    ]
