# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_auto_20180418_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='大小'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='speed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='vender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='厂商'),
        ),
    ]
