# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0022_auto_20180418_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='app_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='应用描述'),
        ),
        migrations.AlterField(
            model_name='host',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='host',
            name='productname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机器型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SN码'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='厂商名称'),
        ),
    ]
