# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0021_auto_20180418_0301'),
        ('servers', '0023_auto_20180418_0241'),
    ]

    operations = [
    ]
