# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0024_merge_20180419_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('server', '服务器'), ('network', '网络设备'), ('storage', '存储设备'), ('security', '机房设备'), ('software', '软件资产'), ('others', '其它类')], default='server', max_length=20, verbose_name='类型')),
                ('ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('note', models.CharField(max_length=100, verbose_name='记录情况')),
                ('event', models.SmallIntegerField(choices=[(1, '硬件变更'), (2, '新增配件'), (3, '设备下线'), (4, '设备上线'), (5, '定期维护'), (6, '业务上线\\更新\\变更'), (7, '其它')], default=1, verbose_name='事件类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='u',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='U数'),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.EngineRoom', verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器')], default='1', max_length=30, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], default='1', max_length=30, null=True, verbose_name='设备状态'),
        ),
    ]
