# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0025_auto_20180425_0709'),
        ('IPpool', '0005_auto_20180413_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('start_ip', models.CharField(default='只填最后一位就可以', max_length=10, verbose_name='起始地址')),
                ('end_ip', models.CharField(default='只填最后一位就可以', max_length=10, verbose_name='结束地址')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], default='1', max_length=30, null=True, verbose_name='设备状态')),
                ('asset_type', models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器')], default='1', max_length=30, null=True, verbose_name='设备类型')),
                ('zabbix', models.CharField(blank=True, max_length=100, null=True, verbose_name='zabbix模版')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ippool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPpool.IPpool', verbose_name='IP资源池')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Team', verbose_name='所属项目')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
