# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 16:56
from __future__ import unicode_literals

from django.db import migrations
import utils.jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='zabbix',
            field=utils.jsonfield.fields.JSONCharField(blank=True, max_length=100, null=True, verbose_name='zabbix模版'),
        ),
    ]
