# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20180511_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='zabbix',
        ),
    ]
