# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0018_merge_20180413_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='主机名')),
                ('mange_ip', models.GenericIPAddressField(verbose_name='管理IP')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='所在位置')),
                ('head', models.CharField(blank=True, max_length=10, null=True, verbose_name='存储机头')),
                ('expansion', models.CharField(blank=True, max_length=10, null=True, verbose_name='存储扩展柜')),
                ('disk_type', models.CharField(choices=[('1', 'SAS'), ('2', '机械')], max_length=10, verbose_name='硬盘类型')),
                ('disk_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='硬盘数量')),
                ('inter_type', models.CharField(choices=[('1', 'SAS'), ('2', '机械')], max_length=10, verbose_name='接口类型')),
                ('inter_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='接口数量')),
                ('maintenance', models.CharField(blank=True, max_length=10, null=True, verbose_name='维保信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Cabinet', verbose_name='所在机柜')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
