# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20180418_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=30, null=True, verbose_name='设备状态'),
        ),
    ]
