# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_storage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='u',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='U数'),
        ),
    ]
