# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storage_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='u',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='U数'),
        ),
    ]
