# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20180419_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
