# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdetail',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
