# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPpool', '0002_auto_20180411_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdetail',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
