# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IPpool', '0003_auto_20180411_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdetail',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelOptions(
            name='ippool',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='ipdetail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ippool',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ippool',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
