# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IPpool', '0004_auto_20180412_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdetail',
            name='ippool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPpool.IPpool', verbose_name='网段'),
        ),
    ]
